#
# メインコンテナ
#
main:
  image: gendosu/milkode
#  build: .

  volumes:
   - .:/products

  ports:
    - "9292:9292"

  links:
    - "redis:redis"

  command: bundle exec milk web -n -o 0.0.0.0

redis:
  image: redis

  ports:
    - "6379:6379"
