#
# メインコンテナ
#
main:
  image: gendosu/milkode
#  build: .

  volumes:
   - .:/products

  ports:
    - "9000:9000"
    - "9292:9292"

  links:
    - "redis:redis"

  command: bundle exec /products/run.sh

redis:
  image: redis

  ports:
    - "6379:6379"
